CREATE TABLE bookings (
    id SERIAL PRIMARY KEY,
    price smallint,
    max smallint,
    minstay smallint,
    stars numeric(4,2),
    numratings smallint,
    "1" boolean,
    "2" boolean,
    "3" boolean,
    "4" boolean,
    "5" boolean,
    "6" boolean,
    "7" boolean,
    "8" boolean,
    "9" boolean,
    "10" boolean,
    "11" boolean,
    "12" boolean,
    "13" boolean,
    "14" boolean,
    "15" boolean,
    "16" boolean,
    "17" boolean,
    "18" boolean,
    "19" boolean,
    "20" boolean,
    "21" boolean,
    "22" boolean,
    "23" boolean,
    "24" boolean,
    "25" boolean,
    "26" boolean,
    "27" boolean,
    "28" boolean,
    "29" boolean,
    "30" boolean,
    "31" boolean,
    "32" boolean,
    "33" boolean,
    "34" boolean,
    "35" boolean,
    "36" boolean,
    "37" boolean,
    "38" boolean,
    "39" boolean,
    "40" boolean,
    "41" boolean,
    "42" boolean,
    "43" boolean,
    "44" boolean,
    "45" boolean,
    "46" boolean,
    "47" boolean,
    "48" boolean,
    "49" boolean,
    "50" boolean,
    "51" boolean,
    "52" boolean,
    "53" boolean,
    "54" boolean,
    "55" boolean,
    "56" boolean,
    "57" boolean,
    "58" boolean,
    "59" boolean,
    "60" boolean,
    "61" boolean,
    "62" boolean,
    "63" boolean,
    "64" boolean,
    "65" boolean,
    "66" boolean,
    "67" boolean,
    "68" boolean,
    "69" boolean,
    "70" boolean,
    "71" boolean,
    "72" boolean,
    "73" boolean,
    "74" boolean,
    "75" boolean,
    "76" boolean,
    "77" boolean,
    "78" boolean,
    "79" boolean,
    "80" boolean,
    "81" boolean,
    "82" boolean,
    "83" boolean,
    "84" boolean,
    "85" boolean,
    "86" boolean,
    "87" boolean,
    "88" boolean,
    "89" boolean,
    "90" boolean
);

CREATE UNIQUE INDEX bookings_pkey ON bookings(id int4_ops);

CREATE TABLE "bookingOneColumn" (
    id integer DEFAULT nextval('"bookingTestOneColumn_id_seq"'::regclass) PRIMARY KEY,
    data text
);

CREATE UNIQUE INDEX "bookingOneColumn_pkey" ON "bookingTestOneColumn"(id int4_ops);

